### ISSUE TITLE
Adapter discovers explicit TestCase without skip details

### ISSUE THREAD

**Issue by yaakov-h** [nunit/nunit3-vs-adapter#530]
Hi all,

I have a custom program that wraps the Visual Studio Test Platform using `IVsTestConsoleWrapper` as demonstrated in the [VSTest samples](https://github.com/Microsoft/vstest/tree/master/samples/Microsoft.TestPlatform.TranslationLayer.E2ETest). This enables our in-house CI system to run unit tests for .NET Core with more advanced functionality than `dotnet` can provide.

We're using NUnit 3.10.1 and NUnit3TestAdapter 3.10.0.

Given the following three test cases:

```csharp
[Ignore("reasons")]
public void IgnoredTest() => Assert.Fail();

[Explicit("reasons")]
public void ExplicitTest() => Assert.Fail();

[TestCase(null, Explicit = true, Reason = "because")]
public void ExplicitTestCase(object ignored) => Assert.Fail("This test should not be run.");
```

VSTest test discovery does not return the first two tests. It does, however, return the third test, but there are no details provided to say "hey you shouldn't run this test".

![image](https://user-images.githubusercontent.com/426009/42740911-94abeac6-88f0-11e8-827a-d6cdc0b71d70.png)

This is inconsistent / un-actionable.

I can't discover the first two tests - which in my case is good, because I don't want to run them.

I do discover the third test, but that's bad, because I don't want to run it, and cannot distinguish it from any other tests that I do want to run.

Is there anything that NUnit can do here to clean this up, or is this an issue for VSTest?

**Comment by OsirisTerje** [comment]
Can you enable the Dump files, see Tips&Tricks https://github.com/nunit/docs/wiki/Tips-And-Tricks  , using a runsettings file, and then upload the results.

**Comment by yaakov-h** [comment]
That's a neat trick!

I've attached the source file and the dumped discovery XML.


[NetCoreNUnitTests_WithDiscoveryDump.zip](https://github.com/nunit/nunit3-vs-adapter/files/2247608/NetCoreNUnitTests_WithDiscoveryDump.zip)

**Comment by yaakov-h** [comment]
> The discovery should always find them (otherwise you would not be able to run any explicit tests), but does the execution run them?

So I'm in a sticky situation here regarding explicit tests. I'm working on a distributed testing system, where we essentially:

1. Discover all tests
2. Analyze the tests and divide them into small groups
3. Get a bunch of machines to run each group of tests

Since the group of tests includes the explicit tests, the test runner will always execute it, since it was explicitly listed.

Therefore, I need a way to filter out ignored and explicit tests at step 2 of the above process, i.e. between discovery and execution.

When I use VSTest's discovery, I get no information about the Explicit attribute or any hints to it's exisence, no `__SKIPREASON`, etc. - see screenshot in OP.

**Comment by OsirisTerje** [comment]
Using the latest adapter (3.10), the explicit tests should also have a category of Explicit.  I tested it again on some test code, and it works as it should.  
![image](https://user-images.githubusercontent.com/203432/43545854-4e9da774-95d7-11e8-867a-d6f230c82b53.png)

This does not work with source based discovery though, but since this is a CI run, you are not using that anyway, that means you're running the discovery phase of the adapter.  As I mentioned above, the adapter adds a category named "Explicit" to all Explicit tests, and you can therefore filter on this category to exclude those tests.

**Comment by yaakov-h** [comment]
`[Explicit]` gets treated as explicit just fine, as shown in your screenshot, but `[TestCase(Explicit = true)]` does not.

I also just noticed - if you look at the NUnit discovery XML, these two tests do not appear to be discovered by NUnit (which would explain why VSTest does not return them).

```csharp
[Ignore("reasons")]
public void IgnoredTest() => Assert.Fail();

[Explicit("reasons")]
public void ExplicitTest() => Assert.Fail();
```

There's definitely an inconsistency between `[Explicit]`/`[Ignore]` and their equivalent `[TestCase]` properties.

**Comment by OsirisTerje** [comment]
@jnm2 Can you take a look at this ?

**Comment by jnm2** [comment]
Happy to!

@yaakov-h 

> I also just noticed - if you look at the NUnit discovery XML, these two tests do not appear to be discovered by NUnit (which would explain why VSTest does not return them).

I was unable to reproduce this with NUnit framework 3.10.1 and the adapter master branch. When framework 3.10.1 explores an assembly with this:

```cs
public class Foo
{
    [TestCase(null, Explicit = true, Reason = "reason")]
    public void Bar(string x) { }
}
```

I get the XML I would expect:

```xml
<test-suite type="TestFixture" id="x1000" name="Foo" fullname="NUnit.Tests.Foo" classname="NUnit.Tests.Foo" runstate="Runnable" testcasecount="1">
  <test-suite type="ParameterizedMethod" id="x1002" name="Bar" fullname="NUnit.Tests.Foo.Bar" classname="NUnit.Tests.Foo" runstate="Runnable" testcasecount="1">
    <test-case id="x1001" name="Bar(null)" fullname="NUnit.Tests.Foo.Bar(null)" methodname="Bar" classname="NUnit.Tests.Foo" runstate="Explicit" seed="553622473">
      <properties>
        <property name="_SKIPREASON" value="reason" />
      </properties>
    </test-case>
  </test-suite>
</test-suite>
```

And when I put that in a unit test just like this test, it passes:

https://github.com/nunit/nunit3-vs-adapter/blob/1af91628171a8792a19a78b7f8ce72cfeab24dd1/src/NUnitTestAdapterTests/TraitsTests.cs#L550-L558

@yaakov-h That's about all I can see. Can you boil down a repro project for us?

**Comment by yaakov-h** [comment]
I'm putting together a full repro project, but in the process I reckon this screenshot should speak for itself...

![image](https://user-images.githubusercontent.com/426009/43754764-c2b71394-9a4f-11e8-94ee-f111f4a96a89.png)

**Comment by yaakov-h** [comment]
Hmm, so it seems that the "Explicit" trait does show up with the latest framework and adapter, though there is no equivalent for "Ignored".

I've uploaded a repro to https://github.com/yaakov-h/NUnitAdapter530Repro.

The output I'm getting is:

```
..\..\Tests\net46\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
        MISSING: Tests.Fixture.IgnoredTestCase
        FOUND: Tests.Fixture.IgnoredTestCase(null)
                Traits:
        MISSING: Tests.Fixture.ExplicitTestCase
        FOUND: Tests.Fixture.ExplicitTestCase(null)
                Traits: Explicit = ""
..\..\Tests\netcoreapp2.0\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
        MISSING: Tests.Fixture.IgnoredTestCase
        FOUND: Tests.Fixture.IgnoredTestCase(null)
                Traits:
        MISSING: Tests.Fixture.ExplicitTestCase
        FOUND: Tests.Fixture.ExplicitTestCase(null)
                Traits: Explicit = ""
```

The output I would expect is either:

```
..\..\Tests\net46\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
..\..\Tests\netcoreapp2.0\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
```

Or:

```
..\..\Tests\net46\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
        FOUND: Tests.Fixture.IgnoredTestCase
                Traits:
        FOUND: Tests.Fixture.IgnoredTestCase(null)
                Traits:
        FOUND: Tests.Fixture.ExplicitTestCase
                Traits: Explicit = ""
        FOUND: Tests.Fixture.ExplicitTestCase(null)
                Traits: Explicit = ""
..\..\Tests\netcoreapp2.0\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
        FOUND: Tests.Fixture.IgnoredTestCase
                Traits:
        FOUND: Tests.Fixture.IgnoredTestCase(null)
                Traits:
        FOUND: Tests.Fixture.ExplicitTestCase
                Traits: Explicit = ""
        FOUND: Tests.Fixture.ExplicitTestCase(null)
                Traits: Explicit = ""
```

with some way to identify the tests that should be Ignored, too.

**Comment by yaakov-h** [comment]
I assume nobody's had a chance to dig into the repro yet?

**Comment by OsirisTerje** [comment]
@jnm2 Can you have a look again at this?

**Comment by jnm2** [comment]
Thanks for the ping; I fell behind. Happy to!

**Comment by jnm2** [comment]
This appears to be a framework bug. Both 3.10.1 and 3.11.0 give:

```xml
<test-suite type="Assembly" id="1008" name="NUnitXmlTest.dll" fullname="NUnitXmlTest.dll" runstate="Runnable" testcasecount="4">
  <properties>
    <property name="_PID" value="38052" />
    <property name="_APPDOMAIN" value="NUnitXmlTest" />
  </properties>
  <test-suite type="TestSuite" id="1009" name="NUnitXmlTest" fullname="NUnitXmlTest" runstate="Runnable" testcasecount="4">
    <test-suite type="TestFixture" id="1000" name="Fixture" fullname="NUnitXmlTest.Fixture" classname="NUnitXmlTest.Fixture" runstate="Runnable" testcasecount="4">
      <test-suite type="ParameterizedMethod" id="1007" name="ExplicitTestCase" fullname="NUnitXmlTest.Fixture.ExplicitTestCase" classname="NUnitXmlTest.Fixture" runstate="Runnable" testcasecount="1">
        <test-case id="1006" name="ExplicitTestCase(null)" fullname="NUnitXmlTest.Fixture.ExplicitTestCase(null)" methodname="ExplicitTestCase" classname="NUnitXmlTest.Fixture" runstate="Explicit" seed="1262453225">
          <properties>
            <property name="_SKIPREASON" value="because" />
          </properties>
        </test-case>
      </test-suite>
      <test-suite type="ParameterizedMethod" id="1005" name="IgnoredTestCase" fullname="NUnitXmlTest.Fixture.IgnoredTestCase" classname="NUnitXmlTest.Fixture" runstate="Runnable" testcasecount="1">
        <test-case id="1004" name="IgnoredTestCase(null)" fullname="NUnitXmlTest.Fixture.IgnoredTestCase(null)" methodname="IgnoredTestCase" classname="NUnitXmlTest.Fixture" runstate="Ignored" seed="1726680985">
          <properties>
            <property name="_SKIPREASON" value="because" />
          </properties>
        </test-case>
      </test-suite>
      <test-case id="1001" name="PassingTest" fullname="NUnitXmlTest.Fixture.PassingTest" methodname="PassingTest" classname="NUnitXmlTest.Fixture" runstate="Runnable" seed="1029543833" />
      <test-suite type="ParameterizedMethod" id="1003" name="PassingTestCase" fullname="NUnitXmlTest.Fixture.PassingTestCase" classname="NUnitXmlTest.Fixture" runstate="Runnable" testcasecount="1">
        <test-case id="1002" name="PassingTestCase(null)" fullname="NUnitXmlTest.Fixture.PassingTestCase(null)" methodname="PassingTestCase" classname="NUnitXmlTest.Fixture" runstate="Runnable" seed="1215827924" />
      </test-suite>
    </test-suite>
  </test-suite>
</test-suite>
```

There's nothing the adapter can do if the framework decides it isn't going to output XML nodes for `IgnoredTest` and `ExplicitTest`!

**Comment by jnm2** [comment]
I just spotted the problem. 😁

@yaakov-h You need to mark the methods as test methods:

```diff
+[Test, Ignore("reasons")]
-[Ignore("reasons")]
 public void IgnoredTest() => Assert.Fail();
 
+[Test, Explicit("reasons")]
-[Explicit("reasons")]
 public void ExplicitTest() => Assert.Fail();
```

Looks like everything is working as expected in 3.10.1 and 3.11.0!

**Comment by yaakov-h** [comment]
Ughhhhhhhhh good catch.

Okay, so after fixing that (repro repo updated), updating NUnit, and getting back to the core issue, I get this output:

```
..\..\Tests\net46\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
        FOUND: Tests.Fixture.IgnoredTest
                Traits:
        FOUND: Tests.Fixture.IgnoredTestCase(null)
                Traits:
        FOUND: Tests.Fixture.ExplicitTest
                Traits: Explicit = ""
        FOUND: Tests.Fixture.ExplicitTestCase(null)
                Traits: Explicit = ""
..\..\Tests\netcoreapp2.0\Tests.dll
        FOUND: Tests.Fixture.PassingTest
                Traits:
        FOUND: Tests.Fixture.PassingTestCase(null)
                Traits:
        FOUND: Tests.Fixture.IgnoredTest
                Traits:
        FOUND: Tests.Fixture.IgnoredTestCase(null)
                Traits:
        FOUND: Tests.Fixture.ExplicitTest
                Traits: Explicit = ""
        FOUND: Tests.Fixture.ExplicitTestCase(null)
                Traits: Explicit = ""
```

I can filter for the trait `Explicit` with an empty value, but my concern has how flipped... there's no way to identify that the _Ignored_ tests should not be run.
