### ISSUE TITLE
Explicit tests are automatically run in Visual Studio 2019 after upgrading from 3.17.0 to 4.0.0-alpha.1

### ISSUE THREAD

**Issue by Stolpe** [nunit/nunit3-vs-adapter#784]
Hi,

About a year ago, I opened #658 that describes how tests marked with `[Expicit]` runs automatically in Visual Studio 2019. This was recently closed, while I was unable to follow it.

While the proposed fix (released as version 4.0.0-alpha.1) does fix the most common cases, it appears that the issue still remains with tests using `[TestCaseSource]`.

- NUnit test adapter 4.0.0-alpha.1
- https://github.com/Stolpe/NUnitExplicitTest/tree/testcasesource

I did write this as a comment in the original issue at https://github.com/nunit/nunit3-vs-adapter/issues/658#issuecomment-689575251, but it appears that this has gone unnoticed (which I fully understand).

**Comment by OsirisTerje** [comment]
Hi and Thanks ! !  Not unnoticed, just out of time to react :-)  But, I wanted to ask you to create a new issue for this, and now you've done that, you saved me some work :-)

**Comment by OsirisTerje** [comment]
Just tested this in Visual Studio, and it works there:

Run All:
![image](https://user-images.githubusercontent.com/203432/93205368-ff8f0580-f757-11ea-9e88-3b20ec8134cb.png)

Run explicitly the TestCaseSource test:
![image](https://user-images.githubusercontent.com/203432/93205396-0c135e00-f758-11ea-87ac-8b3feb9cd27c.png)

**Comment by Stolpe** [comment]
Hi @OsirisTerje,

When I read your reply, I started up my test repo and ran all tests. Now, all `[Explicit]` tests, including the `[TestCaseSource]` one, were properly skipped. I was starting to doubt my sanity :)

Then, something struck me, and I tried the following:

- Downgrade the test adapter to the latest 3.17.0
- Run the tests. `[Exlicit]` tests fail, as expected
- Upgrade the test adapter to 4.0.0-alpha.1
- Rebuild and run the tests. `[Explicit]` tests still fail (both the `[Test]` one and the `[TestCaseSource]`)
- Restart Visual Studio
- Rebuild and run the tests. `[Explicit]` tests still fail (both the `[Test]` one and the `[TestCaseSource]`)
- Close Visual Studio. Manually remove the bin and obj folders
- Start Visual Studio. Rebuild and run the tests. Now, `[Explicit]` tests are properly skipped

Thus, it seems that the title and description of this case is incorrect. The culprit is not `[TestCaseSource]`, but instead it seems that the old version of the test adapter leaves some artifacts that the alpha version picks up on, which causes `[Explicit]` tests to still be run automatically.

Can you (or anyone) confirm this, and/or do you want me to close this ticket and open a new one with a correct description?

**Comment by OsirisTerje** [comment]
@Stolpe I think you are right.  I assume this could be the VS that doesn't rebuild properly,  a Rebuild all should do the same thing.   It could also be something left in th e.vs folder (did you delete that one too?) 

I don't think we can do anything about this, it is outside the scope of the adapter, either testhost or build system, but I'll notify the MS people about it, and see if there is anything that can be done. 

This ticket is good enough, so just change the title.

**Comment by OsirisTerje** [comment]
@Stolpe I would suggest that you raise an issue on DeveloperCommunity about this, and refer there back to this issue.

**Comment by Stolpe** [comment]
Here is the issue on Developer Community: https://developercommunity.visualstudio.com/content/problem/1189880/clean-solution-leaves-artifacts-from-old-version-o.html

**Comment by krokofant** [comment]
I tried the 4.0.0-beta.1 version with vstest run via Azure PIpelines with machine parallel strategy and all explicit tests and ignored tests I had were executed.
This is an ignored one, which looks really weird with "not executed" while the test took a while...
![image](https://user-images.githubusercontent.com/5908498/109776398-ce6d9900-7c02-11eb-915a-c75c01907646.png)

And this is a explicit one which was also executed:
![image](https://user-images.githubusercontent.com/5908498/109776544-fb21b080-7c02-11eb-883b-6ddd5408d837.png)

**Comment by OsirisTerje** [comment]
@krokofant  1. What is your configuration ?   2.  Hosted build or own build agents?  3.  Can you show the relevant pieces of the yml file, or if classic screenshots of the test task setup ?    4. Does it work in Visual Studio locally ?

**Comment by krokofant** [comment]
@OsirisTerje 
1. Configuration in what sense? The .NET version and platform?
2. These are self-hosted.
3. This is the yaml:
```yaml
- job: be_unit_test_domain_test
  displayName: BE 🧪 DomainTest
  strategy:
      parallel: 3
  steps:
      - checkout: none
      - template: templates/download-artifact.yml
        parameters:
            artifacts:
                - name: DomainTest
      - task: VSTest@2
        displayName: Run tests
        inputs:
            testSelector: testAssemblies
            testAssemblyVer2: |
                DomainTest\DomainTest.dll
            searchFolder: $(Build.ArtifactStagingDirectory)
            vsTestVersion: '16.0'
            failOnMinTestsNotRun: true
            testRunTitle: BE DomainTest
```
4. I have not tried it.

I could try to make a reproducible example using the Microsoft-hosted agents with parallel and non parallel execution. Would you encourage testing this with some other specific configurations?
