### ISSUE TITLE
The active test run was aborted. Reason: Test host process crashed : Unhandled Exception

### ISSUE THREAD

**Issue by jaytonic** [nunit/nunit3-vs-adapter#952]
Hi

* NUnit and NUnit3TestAdapter versions: NUnit 3.12.2, Nunit3TestAdapter 4.1.0
* Visual Studio edition and full version number: (see Help About) VS 2022 Professional 17.0.5
* What .net platform and version is being targeted: .Net 4.7.2
* If TFS/VSTS issue, what version, hosted or on-premises, and what build task you see this in: Azure Devop, agent on Premise, with a @VSTest task

We have one PR that fails due to our tests sets. They only fail with this PR, with the following error:
`The active test run was aborted. Reason: Test host process crashed : Unhandled Exception: System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.`

It always crashes with this error while other branches work fine, so it's definitely something we added on our code that triggers this.

It's always the same exception but not everytime at the same position. We tried to enable diagnostic, but it gives absolutely no additional informations:

```
##[debug]ProxyRunRequest: HandleLogMessage Entered
##[error]RunMessage : The active test run was aborted. Reason: Test host process crashed : Unhandled Exception: System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
##[debug]Processed: ##vso[task.logissue type=error;]RunMessage : The active test run was aborted. Reason: Test host process crashed : Unhandled Exception: System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
```
We use Nunit, and the testing part of our YML is the following:
```
  - task: VSTest@2
    timeoutInMinutes: 180
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '*.Test*.dll'
      searchFolder: '$(System.DefaultWorkingDirectory)/$(buildConfiguration)'
      codeCoverageEnabled: false
      platform: 'Any CPU'
      uiTests: false
      configuration: '$(buildConfiguration)'
      runInParallel: true
      resultsFolder: 'testResults'
      runSettingsFile: '$(Build.SourcesDirectory)\azure-tests.runsettings'
      rerunFailedTests: true
```
The PR is like 200 files and we can't find what could cause the issue, especially since we spent a lot of time testing as its a critical feature for us.

Any idea what we can do to have a better idea of what the problem is? Or what could causes this exception?

I found this message: https://nunit-users.narkive.com/YJ2iWPYN/system-appdomainunloadedexception-attempted-to-access-an-unloaded-appdomain from Charlie Poole, which speak about the legacyUnhandledExceptionPolicy  that could be removed to prevent the tests from crashing, but since our NUnit comes with Nuggets packages, we don't have access to the .config file(and I don't know if there is a way to provide another one to the VSTest task ?

When running ALL tests in visual studio, I don't get any error, but after all the tests are executed, VS seems still indicating doing some job. If I run project by project I don't have this issue.

So my questions:
1) Any way to know which test causes the issue?
2) If it's just an issue that some ressources are not yet completely released, isn't there a way to have just one failing test instead of the whole execution stopped? Or even no error would be better?
